version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NAME=World
    command: ["poetry", "run", "uvicorn", "main:app", "--reload"]

  flutter_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NAME=World
    command: ["flutter", "run", "--release", "-d", "web-server", "--web-hostname", "0.0.0.0", "--web-port", "5000"]
